# Generated by Django 4.0.3 on 2022-04-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
