# Generated by Django 4.0.3 on 2022-04-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_car_color_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(default='', max_length=100),
        ),
    ]
