# Generated by Django 4.0.3 on 2022-04-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_options_car_fuel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
        migrations.AddField(
            model_name='car',
            name='options',
            field=models.ManyToManyField(to='main_app.option'),
        ),
    ]
